//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthAndDrive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthAndDrive.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string AlertsPage_Alerts {
            get {
                return ResourceManager.GetString("AlertsPage_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the blood glucose values.
        /// </summary>
        internal static string AlertsPage_EnterValues {
            get {
                return ResourceManager.GetString("AlertsPage_EnterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage alerts.
        /// </summary>
        internal static string AlertsPage_ManageAlerts {
            get {
                return ResourceManager.GetString("AlertsPage_ManageAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max glucose.
        /// </summary>
        internal static string AlertsPage_MaxGlucose {
            get {
                return ResourceManager.GetString("AlertsPage_MaxGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min glucose.
        /// </summary>
        internal static string AlertsPage_MinGlucose {
            get {
                return ResourceManager.GetString("AlertsPage_MinGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALERTS.
        /// </summary>
        internal static string AlertsPage_Title {
            get {
                return ResourceManager.GetString("AlertsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget.
        /// </summary>
        internal static string AlertsPage_Widget {
            get {
                return ResourceManager.GetString("AlertsPage_Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le scan n&apos;a détecté aucun appareil à proximité.
        /// </summary>
        internal static string BluetoothPage_AlertNoDevicesMessage {
            get {
                return ResourceManager.GetString("BluetoothPage_AlertNoDevicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun appareil détecté.
        /// </summary>
        internal static string BluetoothPage_AlertNoDevicesTitle {
            get {
                return ResourceManager.GetString("BluetoothPage_AlertNoDevicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have detected that the bluetooth has stopped. Do you want to reactivate it?.
        /// </summary>
        internal static string BluetoothPage_BluetoothStoppedMessage {
            get {
                return ResourceManager.GetString("BluetoothPage_BluetoothStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt du bluetooth détecté.
        /// </summary>
        internal static string BluetoothPage_BluetoothStoppedTitle {
            get {
                return ResourceManager.GetString("BluetoothPage_BluetoothStoppedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dernière mesure reçue ne permet pas de calibration..
        /// </summary>
        internal static string BluetoothPage_CalibrationPairingError {
            get {
                return ResourceManager.GetString("BluetoothPage_CalibrationPairingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donnée de calibration mise à jour.
        /// </summary>
        internal static string BluetoothPage_CalibrationSaved {
            get {
                return ResourceManager.GetString("BluetoothPage_CalibrationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point d&apos;associer une nouveau matériel. Etes-vous sur de vouloir continuer ?.
        /// </summary>
        internal static string BluetoothPage_ConfirmPairDevice {
            get {
                return ResourceManager.GetString("BluetoothPage_ConfirmPairDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation d&apos;association.
        /// </summary>
        internal static string BluetoothPage_ConfirmPairDeviceTitle {
            get {
                return ResourceManager.GetString("BluetoothPage_ConfirmPairDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue durant l&apos;appairage.
        /// </summary>
        internal static string BluetoothPage_PairingErrorMessage {
            get {
                return ResourceManager.GetString("BluetoothPage_PairingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;appairage.
        /// </summary>
        internal static string BluetoothPage_PairingErrorTitle {
            get {
                return ResourceManager.GetString("BluetoothPage_PairingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;appareil est associé. Nous vous conseillons de procéder à sa calibration.
        /// </summary>
        internal static string BluetoothPage_PairingSuccessMessage {
            get {
                return ResourceManager.GetString("BluetoothPage_PairingSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositif associé.
        /// </summary>
        internal static string BluetoothPage_PairingSuccessTitle {
            get {
                return ResourceManager.GetString("BluetoothPage_PairingSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appareils disponibles.
        /// </summary>
        internal static string BluetoothPage_Tab2_AvailableDevices {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_AvailableDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renseignez la valeur donnée par votre lecteur Freestyle LibreⓇ Afin d’assurer l’étalonnage de vos données dans notre application.
        /// </summary>
        internal static string BluetoothPage_Tab2_CalibrationMessage {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_CalibrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur ajustée.
        /// </summary>
        internal static string BluetoothPage_Tab2_CalibrationRevised {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_CalibrationRevised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur miaomiao.
        /// </summary>
        internal static string BluetoothPage_Tab2_CalibrationSource {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_CalibrationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration de l&apos;appareil.
        /// </summary>
        internal static string BluetoothPage_Tab2_CalibrationTitle {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_CalibrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associer.
        /// </summary>
        internal static string BluetoothPage_Tab2_DeviceActionPair {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_DeviceActionPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        internal static string BluetoothPage_Tab2_DeviceActionScan {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_DeviceActionScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string BluetoothPage_Tab2_DeviceActionStop {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_DeviceActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissocier.
        /// </summary>
        internal static string BluetoothPage_Tab2_DeviceActionUnpair {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_DeviceActionUnpair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun appareil n&apos;est associé. Vous pouvez ajouter un appareil en lançant un scan..
        /// </summary>
        internal static string BluetoothPage_Tab2_NoDeviceBounded {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_NoDeviceBounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appareil associé.
        /// </summary>
        internal static string BluetoothPage_Tab2_PairedDevice {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_PairedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion au dispositif.
        /// </summary>
        internal static string BluetoothPage_Tab2_PairingConnection {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_PairingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation du dispositif.
        /// </summary>
        internal static string BluetoothPage_Tab2_PairingInitialize {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_PairingInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture des dernières mesures.
        /// </summary>
        internal static string BluetoothPage_Tab2_PairingReading {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_PairingReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souscription aux événements de lecture.
        /// </summary>
        internal static string BluetoothPage_Tab2_PairingSubscription {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_PairingSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appairage du dispositif en cours.
        /// </summary>
        internal static string BluetoothPage_Tab2_PairingTitle {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_PairingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion de votre lecteur.
        /// </summary>
        internal static string BluetoothPage_Tab2_Text1 {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procédez comme suit :.
        /// </summary>
        internal static string BluetoothPage_Tab2_Text2 {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Réinitialisez votre lecteur (Miaomiao ou autre) en insérant une tige fine dans la zone Reset sur la partie verso du lecteur..
        /// </summary>
        internal static string BluetoothPage_Tab2_Text3 {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Fixez le lecteur sur votre capteur.
        /// </summary>
        internal static string BluetoothPage_Tab2_Text4 {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Assurez-vous que le bluetooth de votre smartphone soit actif.
        /// </summary>
        internal static string BluetoothPage_Tab2_Text5 {
            get {
                return ResourceManager.GetString("BluetoothPage_Tab2_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLUETOOTH.
        /// </summary>
        internal static string BluetoothPage_Title {
            get {
                return ResourceManager.GetString("BluetoothPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je ne conduis pas.
        /// </summary>
        internal static string DrivePage_DoNotDriveIDontDrive {
            get {
                return ResourceManager.GetString("DrivePage_DoNotDriveIDontDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N’utilisez pas votre téléphone au volant.
        /// </summary>
        internal static string DrivePage_DoNotDriveTitle {
            get {
                return ResourceManager.GetString("DrivePage_DoNotDriveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good journey !.
        /// </summary>
        internal static string DrivePage_GoodJourney {
            get {
                return ResourceManager.GetString("DrivePage_GoodJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez conduire en toute sécurité.
        ///Pensez à faire des pauses régulièrement..
        /// </summary>
        internal static string DrivePage_GoodJourney_Text {
            get {
                return ResourceManager.GetString("DrivePage_GoodJourney_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string DrivePage_High {
            get {
                return ResourceManager.GetString("DrivePage_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez faire une pause immédiatement, vérifier votre glycémie et effectuer les actions nécessaires.
        ///En cas d’urgence appelez le 112..
        /// </summary>
        internal static string DrivePage_HighLow_Text {
            get {
                return ResourceManager.GetString("DrivePage_HighLow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre taux de sucre est anormal.
        /// </summary>
        internal static string DrivePage_HyperDetected {
            get {
                return ResourceManager.GetString("DrivePage_HyperDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévenez les inconforts de conduite.
        /// </summary>
        internal static string DrivePage_HyperState {
            get {
                return ResourceManager.GetString("DrivePage_HyperState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre taux de sucre est anormal.
        /// </summary>
        internal static string DrivePage_HypoDetected {
            get {
                return ResourceManager.GetString("DrivePage_HypoDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez faire une pause immédiatement, vérifier votre glycémie et effectuer les actions nécessaires.
        ///En cas d’urgence appelez le 112..
        /// </summary>
        internal static string DrivePage_HypoHyperDetected_Text {
            get {
                return ResourceManager.GetString("DrivePage_HypoHyperDetected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre glycémie ne permet pas un confort de conduite optimal.
        ///Veuillez faire une pause et vérifier votre glycémie..
        /// </summary>
        internal static string DrivePage_HypoHyperState_Text {
            get {
                return ResourceManager.GetString("DrivePage_HypoHyperState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévenez les inconforts de conduite.
        /// </summary>
        internal static string DrivePage_HypoState {
            get {
                return ResourceManager.GetString("DrivePage_HypoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo.
        /// </summary>
        internal static string DrivePage_Low {
            get {
                return ResourceManager.GetString("DrivePage_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau dangereux pour votre conduite !.
        /// </summary>
        internal static string DrivePage_Stop {
            get {
                return ResourceManager.GetString("DrivePage_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVE.
        /// </summary>
        internal static string DrivePage_Title {
            get {
                return ResourceManager.GetString("DrivePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg/dl.
        /// </summary>
        internal static string DrivePage_Unity {
            get {
                return ResourceManager.GetString("DrivePage_Unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSD.
        /// </summary>
        internal static string HiddenPage_HistoricColumnDSDValue {
            get {
                return ResourceManager.GetString("HiddenPage_HistoricColumnDSDValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permet de visualiser les mesures de l&apos;heure écoulée.
        /// </summary>
        internal static string HiddenPage_HistoricMessage {
            get {
                return ResourceManager.GetString("HiddenPage_HistoricMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string HiddenPage_HistoricOffsetValue {
            get {
                return ResourceManager.GetString("HiddenPage_HistoricOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraichir.
        /// </summary>
        internal static string HiddenPage_HistoricRefresh {
            get {
                return ResourceManager.GetString("HiddenPage_HistoricRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capteur.
        /// </summary>
        internal static string HiddenPage_HistoricSensorValue {
            get {
                return ResourceManager.GetString("HiddenPage_HistoricSensorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique des dernières mesures.
        /// </summary>
        internal static string HiddenPage_HistoricTitle {
            get {
                return ResourceManager.GetString("HiddenPage_HistoricTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette action entrainera la suppression des mesures existantes. Souhaitez-vous continuer ?.
        /// </summary>
        internal static string HiddenPage_LoadConfirmMessage {
            get {
                return ResourceManager.GetString("HiddenPage_LoadConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression des mesures existantes.
        /// </summary>
        internal static string HiddenPage_LoadConfirmTitle {
            get {
                return ResourceManager.GetString("HiddenPage_LoadConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données 100 % &quot;dans la zone&quot;.
        /// </summary>
        internal static string HiddenPage_LoadHistoricalDataInTheZoneBtn {
            get {
                return ResourceManager.GetString("HiddenPage_LoadHistoricalDataInTheZoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données partiellement &quot;dans la zone&quot;.
        /// </summary>
        internal static string HiddenPage_LoadHistoricalDataNotInTheZoneBtn {
            get {
                return ResourceManager.GetString("HiddenPage_LoadHistoricalDataNotInTheZoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permet de charger des données de mesures factices.
        /// </summary>
        internal static string HiddenPage_LoadHistoricalMessage {
            get {
                return ResourceManager.GetString("HiddenPage_LoadHistoricalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesures factices.
        /// </summary>
        internal static string HiddenPage_LoadHistoricalTitle {
            get {
                return ResourceManager.GetString("HiddenPage_LoadHistoricalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simuler.
        /// </summary>
        internal static string HiddenPage_SimulateMeasureBtn {
            get {
                return ResourceManager.GetString("HiddenPage_SimulateMeasureBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure simulée.
        /// </summary>
        internal static string HiddenPage_SimulateMeasurelTitle {
            get {
                return ResourceManager.GetString("HiddenPage_SimulateMeasurelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simuler la réception d&apos;une mesure spécifique.
        /// </summary>
        internal static string HiddenPage_SimulateMeasureMessage {
            get {
                return ResourceManager.GetString("HiddenPage_SimulateMeasureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        internal static string HiddenPage_SimulateValue {
            get {
                return ResourceManager.GetString("HiddenPage_SimulateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGE CACHEE.
        /// </summary>
        internal static string HiddenPage_Title {
            get {
                return ResourceManager.GetString("HiddenPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string HomePage_Alerts {
            get {
                return ResourceManager.GetString("HomePage_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up alerts based on your blood sugar.
        /// </summary>
        internal static string HomePage_Alerts_Text {
            get {
                return ResourceManager.GetString("HomePage_Alerts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        internal static string HomePage_Bluetooth {
            get {
                return ResourceManager.GetString("HomePage_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair your bluetooth player.
        /// </summary>
        internal static string HomePage_Bluetooth_Text {
            get {
                return ResourceManager.GetString("HomePage_Bluetooth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string HomePage_Drive {
            get {
                return ResourceManager.GetString("HomePage_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your blood sugar while driving.
        /// </summary>
        internal static string HomePage_Drive_Text {
            get {
                return ResourceManager.GetString("HomePage_Drive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string HomePage_Rapports {
            get {
                return ResourceManager.GetString("HomePage_Rapports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your data history and export your reports.
        /// </summary>
        internal static string HomePage_Rapports_Text {
            get {
                return ResourceManager.GetString("HomePage_Rapports_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux de sucre anormal : {0} mg/dL.
        /// </summary>
        internal static string NotificationMessageAlertGlycemia {
            get {
                return ResourceManager.GetString("NotificationMessageAlertGlycemia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure de glycémie courante : {0} mg/dL.
        /// </summary>
        internal static string NotificationMessageCurrentMeasure {
            get {
                return ResourceManager.GetString("NotificationMessageCurrentMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions not granted, please restart the app and grant them for the proper functioning of the application.
        /// </summary>
        internal static string Permissions_Message {
            get {
                return ResourceManager.GetString("Permissions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions required.
        /// </summary>
        internal static string Permissions_Title {
            get {
                return ResourceManager.GetString("Permissions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose average.
        /// </summary>
        internal static string ReportsPage_Average {
            get {
                return ResourceManager.GetString("ReportsPage_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the time in the comfort zone.
        /// </summary>
        internal static string ReportsPage_Comfort {
            get {
                return ResourceManager.GetString("ReportsPage_Comfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24H.
        /// </summary>
        internal static string ReportsPage_Day {
            get {
                return ResourceManager.GetString("ReportsPage_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string ReportsPage_DaysInitial {
            get {
                return ResourceManager.GetString("ReportsPage_DaysInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        internal static string ReportsPage_Export {
            get {
                return ResourceManager.GetString("ReportsPage_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15D.
        /// </summary>
        internal static string ReportsPage_HalfMonth {
            get {
                return ResourceManager.GetString("ReportsPage_HalfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30D.
        /// </summary>
        internal static string ReportsPage_Month {
            get {
                return ResourceManager.GetString("ReportsPage_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORTS.
        /// </summary>
        internal static string ReportsPage_Title {
            get {
                return ResourceManager.GetString("ReportsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7D.
        /// </summary>
        internal static string ReportsPage_Week {
            get {
                return ResourceManager.GetString("ReportsPage_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string RootPage_ModifyAccount {
            get {
                return ResourceManager.GetString("RootPage_ModifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string RootPage_NavigateAbout {
            get {
                return ResourceManager.GetString("RootPage_NavigateAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors and trend.
        /// </summary>
        internal static string RootPage_NavigateColors {
            get {
                return ResourceManager.GetString("RootPage_NavigateColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort zone.
        /// </summary>
        internal static string RootPage_NavigateConfort {
            get {
                return ResourceManager.GetString("RootPage_NavigateConfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        internal static string RootPage_NavigateEtalon {
            get {
                return ResourceManager.GetString("RootPage_NavigateEtalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string RootPage_NavigateHelp {
            get {
                return ResourceManager.GetString("RootPage_NavigateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string RootPage_NavigateHome {
            get {
                return ResourceManager.GetString("RootPage_NavigateHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string RootPage_NavigateLanguage {
            get {
                return ResourceManager.GetString("RootPage_NavigateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter ....
        /// </summary>
        internal static string WAIT {
            get {
                return ResourceManager.GetString("WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
